name: Build and Test Airport Ticket Booking System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore "Airport_Ticket_Booking_System/airport_ticket_booking_system.sln"

      - name: Build the solution
        run: dotnet build "Airport_Ticket_Booking_System/airport_ticket_booking_system.sln" --configuration Release

      - name: Run Tests
        run: |
          dotnet test "Airport_Ticket_Booking_System/airport_ticket_booking_system.sln" --no-build --verbosity normal
        env:
          DOTNET_CLI_HOME: $(Build.ArtifactStagingDirectory)
