name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Specify the .NET version you are using

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore AirportTicketBookingSystem/AirportTicketBookingSystem.sln

      # Build the solution
      - name: Build solution
        run: dotnet build AirportTicketBookingSystem/AirportTicketBookingSystem.sln --configuration Release --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test AirportTicketBookingSystem/AirportTicketBookingSystem.sln --no-build --verbosity normal
